### ISSUE TITLE
Unable to resolve reference `System.Private.Uri` on Unity 2021.1.6f1 with v91.2.0

### ISSUE THREAD

**Issue by ryo0ka** [MirageNet/Mirage#804] opened 2021-05-18 17:32 UTC
**Describe the bug**
Installing Mirage package v91.2.0 on Unity 2021.1.6f1 yields 3 errors regarding a missing library `System.Private.Uri`. Samples run in a broken state due to missing scripts.

**Repro project**
https://github.com/Kijibizi/MirageTest

**To Reproduce**
1. Make a new Unity project on 2021.1.6f1
2. Follow instruction on README and install Mirage
3. See logs on console

**Expected behavior**
Package succeeds to install & samples run properly

**Screenshots**
![image](https://user-images.githubusercontent.com/5270319/118696917-bd1f4a80-b849-11eb-991c-737e517cac70.png)
![image](https://user-images.githubusercontent.com/5270319/118697294-1dae8780-b84a-11eb-809b-60d38407dba8.png)

**Desktop (please complete the following information):**
* OS: Windows 10
* Build target: Standalone
* Unity version: 2021.1.6f1
* Mirage version: v91.2.0

**Comment by ryo0ka** [comment] 2021-05-18 17:39
Reproduced with v84.1.1 and onward

Prior to v84.1.1, package won't compile due to `NullReferenceException`:

![image](https://user-images.githubusercontent.com/5270319/118698427-569b2c00-b84b-11eb-8fe0-01669d500a99.png)

In other words none of package versions works

**Comment by Lymdun** [comment] 2021-05-18 17:55
For a bit more of context, this issue is caused by a change from ILPP on 2021.1+ which is used by the weaver. It is using mono cecil, it adds a reference to System.Private.Uri.dll when saving the dll, that is not on the editor. Further investigation is required to see how to become compatible with latest ILPP version (and thus, editor 2021.1+). For now, Mirage supports up to Unity 2020.3.

**Comment by ryo0ka** [comment] 2021-05-19 04:32
sounds good, thanks for the quick response cheers

**Comment by Lymdun** [comment] 2021-05-19 16:40
Re-opening it, since it's an issue we'll need to address anytime soon

**Comment by James-Frowen** [comment] 2021-05-24 17:06
fixed by: https://github.com/MirageNet/Mirage/pull/811

**Closed by James-Frowen** 2021-05-24 17:06 UTC
Labels: bug
